# Generated by Django 3.2.1 on 2021-05-21 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210521_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connecteduser',
            old_name='conn_start',
            new_name='connected',
        ),
    ]
